image: node:18
# This folder is cached between builds
# https://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    # Enables git-lab CI caching. Both .cache and public must be cached, otherwise builds will fail.
    - .cache/
    - public/

stages:
 - Build with gatsby
 - Deploy on Cloudflare

build:
  stage: Build with gatsby
  script:
    - npm install
    - npx gatsby telemetry --disable
    - npx gatsby build --prefix-paths
  only:
    - master
clpages:
  stage: Deploy on Cloudflare
  variables:
    CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
    CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
  script:
    - npm install wrangler
    - npx wrangler pages publish public --project-name www-msbytes-com --commit-dirty=true --branch=master
  artifacts:
    paths:
      - public
  only:
    - master
